<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4SC5RBR" ignored="4" name="XYZ BANK" tests="10" failures="2" timestamp="2020-05-26T13:58:43 IST" time="31.267" errors="0">
  <testcase name="Create_New_Customer" time="5.456" classname="com.infy.practice.testcases.CreateDeleteCustFunctionality"/>
  <testcase name="Verify_Newly_Created_Customer_In_Customer_Table" time="2.677" classname="com.infy.practice.testcases.CreateDeleteCustFunctionality">
    <failure type="java.lang.AssertionError" message="expected [560101] but found [560100]">
      <![CDATA[java.lang.AssertionError: expected [560101] but found [560100]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.infy.practice.pageobjects.CustomersTable.verifyNewCustomerPresentInsideCustomerTable(CustomersTable.java:48)
at com.infy.practice.testcases.CreateDeleteCustFunctionality.Verify_Newly_Created_Customer_In_Customer_Table(CreateDeleteCustFunctionality.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
    </failure>
  </testcase> <!-- Verify_Newly_Created_Customer_In_Customer_Table -->
  <testcase name="Delete_Newly_Created_Customer" time="1.203" classname="com.infy.practice.testcases.CreateDeleteCustFunctionality"/>
  <testcase name="Create_New_Customer_Open_A_Dollar_Account_And_Verify" time="3.021" classname="com.infy.practice.testcases.OpenAccountFunctionality"/>
  <testcase name="Create_New_Customer_Open_A_Pound_Account_And_Verify" time="3.058" classname="com.infy.practice.testcases.OpenAccountFunctionality"/>
  <testcase name="Create_New_Customer_Open_A_Rupee_Account_And_Verify" time="0.043" classname="com.infy.practice.testcases.OpenAccountFunctionality">
    <skipped/>
  </testcase> <!-- Create_New_Customer_Open_A_Rupee_Account_And_Verify -->
  <testcase name="Verify_Initial_Account_Balance" time="1.039" classname="com.infy.practice.testcases.DepositWithdrawFunctionality"/>
  <testcase name="Deposit_Amount_And_Verify" time="0.598" classname="com.infy.practice.testcases.DepositWithdrawFunctionality"/>
  <testcase name="Withdraw_Amount_And_Verify" time="0.678" classname="com.infy.practice.testcases.DepositWithdrawFunctionality"/>
  <testcase name="Withdraw_Amount_More_Than_Balance" time="10.461" classname="com.infy.practice.testcases.DepositWithdrawFunctionality">
    <failure type="java.lang.AssertionError" message="expected [500] but found [600]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [600]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.infy.practice.pageobjects.UserHomePage.verifyAmountAfterWithdrawFailure(UserHomePage.java:135)
at com.infy.practice.testcases.DepositWithdrawFunctionality.Withdraw_Amount_More_Than_Balance(DepositWithdrawFunctionality.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
    </failure>
  </testcase> <!-- Withdraw_Amount_More_Than_Balance -->
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.infy.practice.base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.infy.practice.base.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="com.infy.practice.base.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="com.infy.practice.base.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
</testsuite> <!-- XYZ BANK -->
